apiVersion: v1
kind: Pod
metadata:
  name: example-container
spec:
#  activeDeadlineSeconds: 1800  # Pod terminates after 30 min
  securityContext:
    runAsUser: 260433 # run id command in terminal to get your UID
  containers:
    - name: example-container
      image: ghcr.io/jrhee122/for_kube:main  # image name
      imagePullPolicy: Always
      resources:
        requests: # minimum resources
          memory: "16Gi"
          cpu: "8"
        limits: # maximum resources
          memory: "24Gi"
          cpu: "16"
      volumeMounts:
      - name: home
        mountPath: "/app"
      command: ["/bin/sh"]
      stdin: true
      tty: true
  volumes:
  - name: home
    nfs:
      server: 128.239.56.166
      path: /sciclone/home/jrhee01/in_class_test/for_kube